import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  authors: [{ name: 'Dan Almenar Williams' }],
  creator: 'Dan Almenar Williams',
  publisher: 'Dan Almenar Williams',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
		{/* Google Material Icons */}
		<head>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined"
			rel="stylesheet" />
		</head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
